module.exports = {
   Client: require('./lib/Client'),
   SwiftClient: require('./lib/Client'),

   SwiftGuild: require('./lib/extensions/SwiftGuild'),
   SwiftMessage: require('./lib/extensions/SwiftMessage'),
   SwiftUser: require('./lib/extensions/SwiftUser'),

   PermissionLevels: require('./lib/permissions/PermissionLevels'),

   Schedule: require('./lib/schedule/Schedule'),
   ScheduledTask: require('./lib/schedule/ScheduledTask'),

   Settings: require('./lib/settings/Settings'),
   Gateway: require('./lib/settings/Gateway'),
   GatewayDriver: require('./lib/settings/GatewayDriver'),
   GatewayStorage: require('./lib/settings/GatewayStorage'),
   Schema: require('./lib/settings/schema/Schema'),
   SchemaFolder: require('./lib/settings/schema/SchemaFolder'),
   SchemaPiece: require('./lib/settings/schema/SchemaPiece'),

   AliasPiece: require('./lib/structures/base/AliasPiece'),
   AliasStore: require('./lib/structures/base/AliasStore'),
   Piece: require('./lib/structures/base/Piece'),
   Store: require('./lib/structures/base/Store'),

   Argument: require('./lib/structures/Argument'),
   ArgumentStore: require('./lib/structures/ArgumentStore'),
   Command: require('./lib/structures/Command'),
   CommandStore: require('./lib/structures/CommandStore'),
   Event: require('./lib/structures/Event'),
   EventStore: require('./lib/structures/EventStore'),
   Extendable: require('./lib/structures/Extendable'),
   ExtendableStore: require('./lib/structures/ExtendableStore'),
   Finalizer: require('./lib/structures/Finalizer'),
   FinalizerStore: require('./lib/structures/FinalizerStore'),
   Inhibitor: require('./lib/structures/Inhibitor'),
   InhibitorStore: require('./lib/structures/InhibitorStore'),
   Language: require('./lib/structures/Language'),
   LanguageStore: require('./lib/structures/LanguageStore'),
   Monitor: require('./lib/structures/Monitor'),
   MonitorStore: require('./lib/structures/MonitorStore'),
   MultiArgument: require('./lib/structures/MultiArgument'),
   Provider: require('./lib/structures/Provider'),
   ProviderStore: require('./lib/structures/ProviderStore'),
   Serializer: require('./lib/structures/Serializer'),
   SerializerStore: require('./lib/structures/SerializerStore'),
   SQLProvider: require('./lib/structures/SQLProvider'),
   Task: require('./lib/structures/Task'),
   TaskStore: require('./lib/structures/TaskStore'),

   CommandPrompt: require('./lib/usage/CommandPrompt'),
   CommandUsage: require('./lib/usage/CommandUsage'),
   Usage: require('./lib/usage/Usage'),
   Possible: require('./lib/usage/Possible'),
   Tag: require('./lib/usage/Tag'),
   TextPrompt: require('./lib/usage/TextPrompt'),

   Colors: require('./lib/util/Colors'),
   SwiftConsole: require('./lib/util/SwiftConsole'),
   constants: require('./lib/util/constants'),
   Cron: require('./lib/util/Cron'),
   Duration: require('./lib/util/Duration'),
   QueryBuilder: require('./lib/util/QueryBuilder'),
   RateLimit: require('./lib/util/RateLimit'),
   RateLimitManager: require('./lib/util/RateLimitManager'),
   ReactionHandler: require('./lib/util/ReactionHandler'),
   RichDisplay: require('./lib/util/RichDisplay'),
   RichMenu: require('./lib/util/RichMenu'),
   Stopwatch: require('./lib/util/Stopwatch'),
   Timestamp: require('./lib/util/Timestamp'),
   Type: require('./lib/util/Type'),
   util: require('./lib/util/util'),

   version: require('../package').version
};
